Increased HttpClient's timeout in LocalWorkerService to 180 seconds
SoftUni-Internal/judge-worker pull request #126
Opened 2023-02-14 13:50 UTC by Innos

Closes [#513](https://github.com/SoftUni-Internal/exam-systems-issues/issues/513)

2023-02-16 12:17 UTC, mishogv requested changes
discuss

2023-03-09 15:31 UTC, mishogv approved these changes

2023-03-13 11:20 UTC, shsimeonova submitted a review, later dismissed

2023-03-13 13:55 UTC, shsimeonova approved these changes

2023-03-13 13:55 UTC, mishogv approved these changes

2023-03-13 15:59 UTC, merged