add additional exception type to handle thread exceptions
SoftUni-Internal/judge-worker pull request #168
Opened 2023-11-28 12:24 UTC by MomchilSt

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1066

Linked pull requests from another repos (if any):
https://github.com/SoftUni-Internal/OpenJudgeSystem/pull/942

**Summary of the changes made**:
1. add new exception type (thread)
2. use the new exception type to ExecuteSubmissionRemotely

2023-11-29 09:16 UTC, MTsatsarov approved these changes

2023-11-30 15:03 UTC, gogo4ds requested changes

2023-11-30 15:07 UTC, gogo4ds requested changes

2023-11-30 15:07 UTC, gogo4ds commented on OJS.Workers.SubmissionProcessors/Workers/RemoteSubmissionsWorker.cs
> +            }
I don't see anything different in this catch than in the one below. What's the point of it, besides setting different exception type (which is not needed as mentioned in the previous comment)?

2023-12-05 15:02 UTC, closed without merging